name: Release-please

# Give permissions to the release-please bot to open and update PRs
# and commit to PRs the repository to update Cargo.lock
permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  actions: write
  checks: write

# Run the workflow on push to the main branch and manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Prepare the release PR with changelog updates and create github releases
  # Do not publish to crates.io or upgrade dependencies
  release-please:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@v1
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      update-cargo-lock: true                          # Update Cargo.lock file
      publish-to-crates-io: false                      # Disable publishing to crates.io
      upgrade-dependencies: false                      # Do not upgrade workspace dependencies
      workspace-dirs: 'e2e-tests-rust'                 # Additionally update Cargo.lock in e2e-tests-rust

  # Trigger workflow to publish binaries
  release-binaries:
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    needs: release-please
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit

  test-release-pr:
    needs: release-please
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    runs-on: ubuntu-latest
    steps:

      - name: Trigger testing workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        id: tests-step
        with:
          owner: ${{ github.repository_owner}}
          repo: ${{ github.event.repository.name }}
          workflow_file_name: test.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ fromJson(needs.release-please.outputs.prs)[0].headBranchName }}
          wait_interval: 30
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Report check
        shell: 'bash -ex {0}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=$(gh api repos/${{ github.repository }}/pulls/${{ fromJson(needs.release-please.outputs.prs)[0].number }} --jq '.head.sha')
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/check-runs \
            -f name="Test Check" \
            -f head_sha="${SHA}" \
            -f status="completed" \
            -f "conclusion=${{ steps.tests-step.conclusion }}"
            -f "output[title]=Run tests" \
            -f "output[summary]=Results: ${{ steps.tests-step.conclusion }}"
