name: Release-please

# Give permissions to the release-please bot to open and update PRs
# and commit to PRs the repository to update Cargo.lock
permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  actions: write

# Run the workflow on push to the main branch and manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Prepare the release PR with changelog updates and create github releases
  # Do not publish to crates.io or upgrade dependencies
  release-please:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@v1
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      update-cargo-lock: true                          # Update Cargo.lock file
      publish-to-crates-io: false                      # Disable publishing to crates.io
      upgrade-dependencies: false                      # Do not upgrade workspace dependencies
      workspace-dirs: 'e2e-tests-rust'                 # Additionally update Cargo.lock in e2e-tests-rust

  # Trigger workflow to publish binaries
  release-binaries:
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    needs: release-please
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit

  test:
    needs: release-please
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Test"
          echo '${{ needs.release-please.outputs.prs }}'
          echo '${{ fromJson(needs.release-please.outputs.prs)[0].headBranchName }}'

  test-release-pr:
    needs: release-please
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    runs-on: ubuntu-latest
    steps:

      - name: Trigger testing workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        id: tests-step
        with:
          owner: ${{ github.repository_owner}}
          repo: ${{ github.event.repository.name }}
          workflow_file_name: test.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ fromJson(needs.release-please.outputs.prs)[0].headBranchName }}
          wait_interval: 30
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: get sha from PR number and save output
        id: get-sha
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('PR number: ' + ${{ fromJson(needs.release-please.outputs.prs)[0].number }})
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ fromJson(needs.release-please.outputs.prs)[0].number }}
            })
            console.log('PR Head sha: ' + pr.data.head.sha)
            core.setOutput('sha', pr.data.head.sha)

      - name: Report tests check
        if: ${{ github.event.inputs.used-branch && steps.tests-step.outcome }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.checks.create({
              name: 'test',
              head_sha: '${{ steps.get-sha.outputs.sha }}',
              status: 'completed',
              conclusion: '${{ steps.tests-step.outcome }}',
              output: {
                title: 'Run tests',
                summary: 'Results: ${{ steps.tests-step.outcome }}'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            })
